yarnPath: .yarn/releases/yarn-3.2.0.cjs
packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "firebase@*":
    dependencies:
      "@firebase/auth": "*"
      "@firebase/app": "*"
