name: Compile
on:
  - push
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Install
        run: yarn install
      - name: Generate types
        run: yarn gentypes
      - name: Lint
        run: yarn lint
